packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  # Dev tooling
  eslint: ^9.27.0
  "@eslint/js": ^9.27.0
  "@types/eslint-config-prettier": ^6.11.3
  eslint-config-prettier: ^10.1.5
  eslint-config-turbo: ^2.5.3
  eslint-plugin-import: ^2.31.0
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.5.3
  globals: ^16.1.0
  typescript-eslint: ^8.32.1
  prettier: ^3.5.3
  tailwindcss: ^4.1.7
  typescript: ^5.8.3

  # Misc
  zod: ^3.24.2
  tailwindcss-animate: ^1.0.7

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.69.0
  "@tanstack/react-query-devtools": "^5.66.5"
  "@trpc/client": ^11.1.0
  "@trpc/tanstack-react-query": ^11.1.0
  "@trpc/server": ^11.1.0
catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.12
    "@types/react-dom": ^19.0.4
